import type { Metadata } from "next";
import localFont from "next/font/local";
import { PrimeReactProvider } from "primereact/api";
import { Menubar } from "primereact/menubar";
import Image from "next/image";
import logo from "@/images/just logo transparent.png";
import "primereact/resources/themes/lara-light-cyan/theme.css";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import StoreProvider from "@/lib/components/StoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const endLogo = (
  <div>
    <Image aria-hidden src={logo} alt="File icon" width={24} height={24} />
  </div>
);

const menuOptions = [
  {
    label: "Login",
    url: "/login",
  },
  {
    label: "Sign Up",
    url: "/signup",
  },
  {
    label: "Dashboard",
    url: "/dashboard",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <PrimeReactProvider>
            <Menubar model={menuOptions} end={endLogo} />
            {children}
          </PrimeReactProvider>
          <ToastContainer />
        </StoreProvider>
      </body>
    </html>
  );
}
